<?php
require_once '../includes/config.php';
require_admin();

$user = new User($db);

// Handle actions
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (isset($_POST['action'])) {
        switch ($_POST['action']) {
            case 'update_role':
                $user_id = intval($_POST['user_id']);
                $new_role = $_POST['role'];
                
                $stmt = $db->prepare("UPDATE users SET role = ? WHERE id = ?");
                if ($stmt->execute([$new_role, $user_id])) {
                    $_SESSION['success'] = "User role updated successfully";
                } else {
                    $_SESSION['error'] = "Failed to update user role";
                }
                break;
                
            case 'delete_user':
                $user_id = intval($_POST['user_id']);
                
                // Don't allow deleting current admin
                if ($user_id == get_current_user_id()) {
                    $_SESSION['error'] = "Cannot delete your own account";
                } else {
                    $stmt = $db->prepare("DELETE FROM users WHERE id = ?");
                    if ($stmt->execute([$user_id])) {
                        $_SESSION['success'] = "User deleted successfully";
                    } else {
                        $_SESSION['error'] = "Failed to delete user";
                    }
                }
                break;
                
            case 'write_user_info':
                $user_id = intval($_POST['user_id']);
                $user_info = $_POST['user_info'];
                
                // Get user data
                $stmt = $db->prepare("SELECT * FROM users WHERE id = ?");
                $stmt->execute([$user_id]);
                $user_data = $stmt->fetch();
                
                if ($user_data) {
                    $filename = 'user_info_' . $user_id . '_' . date('Y-m-d_H-i-s') . '.txt';
                    $filepath = '../uploads/user_info/' . $filename;
                    
                    // Create directory if not exists
                    if (!is_dir(dirname($filepath))) {
                        mkdir(dirname($filepath), 0755, true);
                    }
                    
                    $content = "User Information Report\n";
                    $content .= "Generated: " . date('Y-m-d H:i:s') . "\n";
                    $content .= "Generated by: " . $_SESSION['user_name'] . "\n\n";
                    $content .= "User ID: " . $user_data['id'] . "\n";
                    $content .= "Name: " . $user_data['first_name'] . " " . $user_data['last_name'] . "\n";
                    $content .= "Email: " . $user_data['email'] . "\n";
                    $content .= "Role: " . $user_data['role'] . "\n";
                    $content .= "Registered: " . $user_data['created_at'] . "\n\n";
                    $content .= "Additional Information:\n" . $user_info . "\n";
                    
                    if (file_put_contents($filepath, $content)) {
                        $_SESSION['success'] = "User information saved to file: " . $filename;
                    } else {
                        $_SESSION['error'] = "Failed to save user information";
                    }
                }
                break;
        }
        header('Location: users.php');
        exit;
    }
}

// Get users with pagination
$page = isset($_GET['page']) ? max(1, intval($_GET['page'])) : 1;
$per_page = 15;
$offset = ($page - 1) * $per_page;

$search = isset($_GET['search']) ? trim($_GET['search']) : '';
$role_filter = isset($_GET['role']) ? $_GET['role'] : '';

$where_conditions = [];
$params = [];

if ($search) {
    $where_conditions[] = "(first_name LIKE ? OR last_name LIKE ? OR email LIKE ?)";
    $params[] = "%$search%";
    $params[] = "%$search%";
    $params[] = "%$search%";
}

if ($role_filter) {
    $where_conditions[] = "role = ?";
    $params[] = $role_filter;
}

$where_clause = !empty($where_conditions) ? 'WHERE ' . implode(' AND ', $where_conditions) : '';

$sql = "SELECT * FROM users $where_clause ORDER BY created_at DESC LIMIT $per_page OFFSET $offset";
$stmt = $db->prepare($sql);
$stmt->execute($params);
$users = $stmt->fetchAll();

// Get total count
$count_sql = "SELECT COUNT(*) as total FROM users $where_clause";
$count_stmt = $db->prepare($count_sql);
$count_stmt->execute($params);
$total_users = $count_stmt->fetch()['total'];
$total_pages = ceil($total_users / $per_page);
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Users Management - <?php echo SITE_NAME; ?></title>
    
    <link rel="stylesheet" href="../css/admin_index.css">
    <link rel="stylesheet" href="../css/style.css">
    <link rel="stylesheet" href="../css/admin_users.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    
</head>
<body>
    <div class="admin-header">
        <div class="container">
            <h1>Users Management</h1>
        </div>
    </div>
    
    <nav class="admin-nav">
        <div class="container">
            <ul>
                <li><a href="index.php">Dashboard</a></li>
                <li><a href="products.php">Products</a></li>
                <li><a href="users.php" class="active">Users</a></li>
                <li><a href="orders.php">Orders</a></li>
                <li><a href="../index.php">View Site</a></li>
                <li><a href="../logout.php">Logout</a></li>
            </ul>
        </div>
    </nav>
    
    <div class="container">
        <!-- Filters -->
        <form method="GET" class="filters">
            <input type="text" name="search" placeholder="Search users..." 
                   value="<?php echo htmlspecialchars($search); ?>" class="search-input">
            <select name="role" class="form-select" style="width: auto;">
                <option value="">All Roles</option>
                <option value="admin" <?php echo $role_filter === 'admin' ? 'selected' : ''; ?>>Admin</option>
                <option value="customer" <?php echo $role_filter === 'customer' ? 'selected' : ''; ?>>Customer</option>
            </select>
            <button type="submit" class="btn btn-primary">Filter</button>
            <a href="users.php" class="btn">Clear</a>
        </form>

        <!-- Users Table -->
        <div class="admin-card">
            <div class="card-header">
                <h3>Users (<?php echo number_format($total_users); ?> total)</h3>
            </div>
            <table class="users-table">
                <thead>
                    <tr>
                        <th>User</th>
                        <th>Email</th>
                        <th>Role</th>
                        <th>Registered</th>
                        <th>Status</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($users as $u): ?>
                        <tr>
                            <td>
                                <div style="display: flex; align-items: center; gap: 10px;">
                                    <div class="avatar">
                                        <?php echo strtoupper(substr($u['first_name'], 0, 1)); ?>
                                    </div>
                                    <div>
                                        <strong><?php echo htmlspecialchars($u['first_name'] . ' ' . $u['last_name']); ?></strong>
                                        <?php if ($u['phone']): ?>
                                            <br><small style="color: #6B7280;"><?php echo htmlspecialchars($u['phone']); ?></small>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </td>
                            <td><?php echo htmlspecialchars($u['email']); ?></td>
                            <td>
                                <span class="role-badge role-<?php echo $u['role']; ?>">
                                    <?php echo ucfirst($u['role']); ?>
                                </span>
                            </td>
                            <td><?php echo date('M j, Y', strtotime($u['created_at'])); ?></td>
                            <td>
                                <?php if ($u['email_verified']): ?>
                                    <span style="color: #10B981;">✓ Verified</span>
                                <?php else: ?>
                                    <span style="color: #EF4444;">✗ Unverified</span>
                                <?php endif; ?>
                            </td>
                            <td>
                                <button onclick="changeRole(<?php echo $u['id']; ?>, '<?php echo $u['role']; ?>')" class="btn btn-warning">
                                    Change Role
                                </button>
                                <button onclick="writeUserInfo(<?php echo $u['id']; ?>, '<?php echo htmlspecialchars($u['first_name'] . ' ' . $u['last_name']); ?>')" class="btn btn-success">
                                    Write Info
                                </button>
                                <?php if ($u['id'] != get_current_user_id()): ?>
                                    <button onclick="deleteUser(<?php echo $u['id']; ?>, '<?php echo htmlspecialchars($u['first_name'] . ' ' . $u['last_name']); ?>')" class="btn btn-danger">
                                        Delete
                                    </button>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>

        <!-- Pagination -->
        <?php if ($total_pages > 1): ?>
            <div style="display: flex; justify-content: center; margin-top: 2rem; gap: 0.5rem;">
                <?php for ($i = 1; $i <= $total_pages; $i++): ?>
                    <a href="?page=<?php echo $i; ?>&search=<?php echo urlencode($search); ?>&role=<?php echo urlencode($role_filter); ?>" 
                       class="btn <?php echo $i === $page ? 'btn-primary' : ''; ?>"><?php echo $i; ?></a>
                <?php endfor; ?>
            </div>
        <?php endif; ?>
    </div>

    <!-- Change Role Modal -->
    <div id="roleModal" class="modal">
        <div class="modal-content">
            <h2>Change User Role</h2>
            <form method="POST">
                <input type="hidden" name="action" value="update_role">
                <input type="hidden" name="user_id" id="role_user_id">
                
                <div class="form-group">
                    <label class="form-label">Select New Role</label>
                    <select name="role" id="role_select" class="form-select" required>
                        <option value="customer">Customer</option>
                        <option value="admin">Admin</option>
                    </select>
                </div>
                
                <div style="display: flex; gap: 1rem; margin-top: 2rem;">
                    <button type="submit" class="btn btn-success">Update Role</button>
                    <button type="button" onclick="closeModal('roleModal')" class="btn">Cancel</button>
                </div>
            </form>
        </div>
    </div>

    <!-- Write User Info Modal -->
    <div id="infoModal" class="modal">
        <div class="modal-content">
            <h2>Write User Information</h2>
            <form method="POST">
                <input type="hidden" name="action" value="write_user_info">
                <input type="hidden" name="user_id" id="info_user_id">
                
                <div class="form-group">
                    <label class="form-label">User: <span id="info_user_name"></span></label>
                </div>
                
                <div class="form-group">
                    <label class="form-label">Additional Information</label>
                    <textarea name="user_info" class="form-textarea" placeholder="Enter any additional information about this user..." required style="height: 150px;"></textarea>
                </div>
                
                <div style="display: flex; gap: 1rem; margin-top: 2rem;">
                    <button type="submit" class="btn btn-success">Save to File</button>
                    <button type="button" onclick="closeModal('infoModal')" class="btn">Cancel</button>
                </div>
            </form>
        </div>
    </div>

    <script>
        function openModal(modalId) {
            document.getElementById(modalId).style.display = 'block';
        }

        function closeModal(modalId) {
            document.getElementById(modalId).style.display = 'none';
        }

        function changeRole(userId, currentRole) {
            document.getElementById('role_user_id').value = userId;
            document.getElementById('role_select').value = currentRole;
            openModal('roleModal');
        }

        function writeUserInfo(userId, userName) {
            document.getElementById('info_user_id').value = userId;
            document.getElementById('info_user_name').textContent = userName;
            openModal('infoModal');
        }

        function deleteUser(userId, userName) {
            if (confirm(`Are you sure you want to delete user "${userName}"? This action cannot be undone.`)) {
                const form = document.createElement('form');
                form.method = 'POST';
                form.innerHTML = `
                    <input type="hidden" name="action" value="delete_user">
                    <input type="hidden" name="user_id" value="${userId}">
                `;
                document.body.appendChild(form);
                form.submit();
            }
        }

        // Close modal when clicking outside
        window.onclick = function(event) {
            if (event.target.classList.contains('modal')) {
                event.target.style.display = 'none';
            }
        }
    </script>

    <!-- Display Messages -->
    <?php if (isset($_SESSION['success'])): ?>
        <div class="alert alert-success" style="position: fixed; top: 20px; right: 20px; z-index: 10000; padding: 12px 20px; border-radius: 8px; background: #D1FAE5; border: 1px solid #10B981; color: #065F46;">
            <?php echo $_SESSION['success']; unset($_SESSION['success']); ?>
        </div>
    <?php endif; ?>

    <?php if (isset($_SESSION['error'])): ?>
        <div class="alert alert-error" style="position: fixed; top: 20px; right: 20px; z-index: 10000; padding: 12px 20px; border-radius: 8px; background: #FEE2E2; border: 1px solid #EF4444; color: #991B1B;">
            <?php echo $_SESSION['error']; unset($_SESSION['error']); ?>
        </div>
    <?php endif; ?>

    <script>
        // Auto-hide alerts
        setTimeout(function() {
            const alerts = document.querySelectorAll('.alert');
            alerts.forEach(alert => alert.style.display = 'none');
        }, 5000);
    </script>
</body>
</html>